In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('E:\mckayjohns\data\europaFinal.csv')

In [4]:
df.head()

,minute,second,teamId,x,y,period,type,outcome,playerId,endX,endY
0,0,0.0,Manchester United,0.0,0.0,FirstHalf,Start,Successful,NaN,NaN,NaN
1,0,0.0,Villarreal,0.0,0.0,FirstHalf,Start,Successful,NaN,NaN,NaN
2,0,0.0,Manchester United,49.9,50.0,FirstHalf,Pass,Successful,18.0,31.5,59.6
3,0,3.0,Manchester United,32.2,58.1,FirstHalf,Pass,Unsuccessful,2.0,69.6,100.0
4,0,32.0,Villarreal,34.4,0.0,FirstHalf,Pass,Successful,8.0,36.5,9.5

In [5]:
df = df.loc[(df['teamId']=='Manchester United') & (df['playerId']==18) & (df['type']=='Pass') & (df['outcome']=='Successful')]

In [6]:
df.head()

,minute,second,teamId,x,y,period,type,outcome,playerId,endX,endY
2,0,0.0,Manchester United,49.9,50.0,FirstHalf,Pass,Successful,18.0,31.5,59.6
119,6,11.0,Manchester United,65.4,96.8,FirstHalf,Pass,Successful,18.0,63.3,87.8
130,6,55.0,Manchester United,69.8,30.3,FirstHalf,Pass,Successful,18.0,74.4,18.8
133,7,1.0,Manchester United,84.3,23.3,FirstHalf,Pass,Successful,18.0,86.0,20.0
185,12,20.0,Manchester United,39.0,64.8,FirstHalf,Pass,Successful,18.0,32.8,72.9

In [11]:
xT = pd.read_csv('E:/mckayjohns/data/xT_Grid.csv', header=None)

In [13]:
xT = np.array(xT)

In [14]:
xT

array([[0.00638303, 0.00779616, 0.00844854, 0.00977659, 0.01126267,
        0.01248344, 0.01473596, 0.0174506 , 0.02122129, 0.02756312,
        0.03485072, 0.0379259 ],
       [0.00750072, 0.00878589, 0.00942382, 0.0105949 , 0.01214719,
        0.0138454 , 0.01611813, 0.01870347, 0.02401521, 0.02953272,
        0.04066992, 0.04647721],
       [0.0088799 , 0.00977745, 0.01001304, 0.01110462, 0.01269174,
        0.01429128, 0.01685596, 0.01935132, 0.0241224 , 0.02855202,
        0.05491138, 0.06442595],
       [0.00941056, 0.01082722, 0.01016549, 0.01132376, 0.01262646,
        0.01484598, 0.01689528, 0.0199707 , 0.02385149, 0.03511326,
        0.10805102, 0.25745362],
       [0.00941056, 0.01082722, 0.01016549, 0.01132376, 0.01262646,
        0.01484598, 0.01689528, 0.0199707 , 0.02385149, 0.03511326,
        0.10805102, 0.25745362],
       [0.0088799 , 0.00977745, 0.01001304, 0.01110462, 0.01269174,
        0.01429128, 0.01685596, 0.01935132, 0.0241224 , 0.02855202,
        0.05491138, 0.06442595],
       [0.00750072, 0.00878589, 0.00942382, 0.0105949 , 0.01214719,
        0.0138454 , 0.01611813, 0.01870347, 0.02401521, 0.02953272,
        0.04066992, 0.04647721],
       [0.00638303, 0.00779616, 0.00844854, 0.00977659, 0.01126267,
        0.01248344, 0.01473596, 0.0174506 , 0.02122129, 0.02756312,
        0.03485072, 0.0379259 ]])

In [19]:
#make into shape

xT_rows,xTcols = xT.shape

In [21]:
# change into 8-12 format


df['x1_bin'] = pd.cut(df['x'],bins = xTcols, labels = False)
df['y1_bin'] = pd.cut(df['y'],bins = xT_rows, labels = False)
df['x2_bin'] = pd.cut(df['endX'],bins = xTcols, labels = False)
df['y2_bin'] = pd.cut(df['endY'],bins = xT_rows, labels = False)

<ipython-input-21-27c7854373e6>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['x1_bin'] = pd.cut(df['x'],bins = xTcols, labels = False)
<ipython-input-21-27c7854373e6>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['y1_bin'] = pd.cut(df['y'],bins = xT_rows, labels = False)
<ipython-input-21-27c7854373e6>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['x2_bin'] = pd.cut(df['endX'],bins = xTcols, labels = False)
<ipython-input-21-27c7854373e6>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['y2_bin'] = pd.cut(df['endY'],bins = xT_rows, labels = False)

In [23]:
df.head(25)

,minute,second,teamId,x,y,period,type,outcome,playerId,endX,endY,x1_bin,y1_bin,x2_bin,y2_bin
2,0,0.0,Manchester United,49.9,50.0,FirstHalf,Pass,Successful,18.0,31.5,59.6,5,4,3,4
119,6,11.0,Manchester United,65.4,96.8,FirstHalf,Pass,Successful,18.0,63.3,87.8,7,7,7,7
130,6,55.0,Manchester United,69.8,30.3,FirstHalf,Pass,Successful,18.0,74.4,18.8,8,2,9,1
133,7,1.0,Manchester United,84.3,23.3,FirstHalf,Pass,Successful,18.0,86.0,20.0,10,1,10,1
185,12,20.0,Manchester United,39.0,64.8,FirstHalf,Pass,Successful,18.0,32.8,72.9,3,5,3,5
197,12,50.0,Manchester United,43.0,70.0,FirstHalf,Pass,Successful,18.0,41.0,96.9,4,5,4,7
286,19,9.0,Manchester United,69.5,74.5,FirstHalf,Pass,Successful,18.0,59.9,71.1,8,6,7,5
336,22,57.0,Manchester United,37.0,89.6,FirstHalf,Pass,Successful,18.0,32.8,81.4,3,7,3,6
366,24,43.0,Manchester United,71.7,24.6,FirstHalf,Pass,Successful,18.0,70.9,9.7,8,1,8,0
434,30,5.0,Manchester United,49.9,50.1,FirstHalf,Pass,Successful,18.0,31.0,40.7,5,4,3,3
473,31,58.0,Manchester United,65.4,77.9,FirstHalf,Pass,Successful,18.0,83.0,84.8,7,6,10,6
514,33,31.0,Manchester United,64.9,76.7,FirstHalf,Pass,Successful,18.0,47.7,67.3,7,6,5,5
516,33,37.0,Manchester United,59.8,88.1,FirstHalf,Pass,Successful,18.0,47.8,66.1,7,7,5,5
523,34,4.0,Manchester United,69.6,73.6,FirstHalf,Pass,Successful,18.0,65.3,86.6,8,6,7,7
581,37,3.0,Manchester United,58.8,94.2,FirstHalf,Pass,Successful,18.0,71.0,97.2,6,7,8,7
676,42,12.0,Manchester United,65.8,70.9,FirstHalf,Pass,Successful,18.0,58.9,71.2,8,5,7,5
679,42,21.0,Manchester United,60.9,69.4,FirstHalf,Pass,Successful,18.0,63.1,53.0,7,5,7,4
716,44,12.0,Manchester United,70.1,26.8,FirstHalf,Pass,Successful,18.0,65.0,19.7,8,2,7,1
752,45,12.0,Manchester United,67.9,29.1,FirstHalf,Pass,Successful,18.0,57.1,11.7,8,2,6,0
789,45,31.0,Manchester United,37.6,80.9,SecondHalf,Pass,Successful,18.0,38.4,87.4,3,6,4,7
838,47,46.0,Manchester United,24.3,65.1,SecondHalf,Pass,Successful,18.0,29.2,36.7,1,5,3,2
879,49,22.0,Manchester United,41.5,9.2,SecondHalf,Pass,Successful,18.0,47.7,14.3,4,0,5,1
884,49,34.0,Manchester United,56.5,7.7,SecondHalf,Pass,Successful,18.0,45.1,61.7,6,0,5,5
887,49,46.0,Manchester United,70.3,33.9,SecondHalf,Pass,Successful,18.0,74.7,27.1,8,2,9,2
970,56,26.0,Manchester United,63.8,18.2,SecondHalf,Pass,Successful,18.0,77.2,3.2,7,1,9,0

In [26]:
df['start_zone_value'] = df[['x1_bin','y1_bin']].apply(lambda x: xT[x[1]][x[0]], axis=1)
df['end_zone_value'] = df[['x2_bin','y2_bin']].apply(lambda x: xT[x[1]][x[0]], axis=1)

<ipython-input-26-39f74ed3c269>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['start_zone_value'] = df[['x1_bin','y1_bin']].apply(lambda x: xT[x[1]][x[0]], axis=1)
<ipython-input-26-39f74ed3c269>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['end_zone_value'] = df[['x2_bin','y2_bin']].apply(lambda x: xT[x[1]][x[0]], axis=1)

In [27]:
df.head(25)

,minute,second,teamId,x,y,period,type,outcome,playerId,endX,endY,x1_bin,y1_bin,x2_bin,y2_bin,start_zone_value,end_zone_value
2,0,0.0,Manchester United,49.9,50.0,FirstHalf,Pass,Successful,18.0,31.5,59.6,5,4,3,4,0.014846,0.011324
119,6,11.0,Manchester United,65.4,96.8,FirstHalf,Pass,Successful,18.0,63.3,87.8,7,7,7,7,0.017451,0.017451
130,6,55.0,Manchester United,69.8,30.3,FirstHalf,Pass,Successful,18.0,74.4,18.8,8,2,9,1,0.024122,0.029533
133,7,1.0,Manchester United,84.3,23.3,FirstHalf,Pass,Successful,18.0,86.0,20.0,10,1,10,1,0.040670,0.040670
185,12,20.0,Manchester United,39.0,64.8,FirstHalf,Pass,Successful,18.0,32.8,72.9,3,5,3,5,0.011105,0.011105
197,12,50.0,Manchester United,43.0,70.0,FirstHalf,Pass,Successful,18.0,41.0,96.9,4,5,4,7,0.012692,0.011263
286,19,9.0,Manchester United,69.5,74.5,FirstHalf,Pass,Successful,18.0,59.9,71.1,8,6,7,5,0.024015,0.019351
336,22,57.0,Manchester United,37.0,89.6,FirstHalf,Pass,Successful,18.0,32.8,81.4,3,7,3,6,0.009777,0.010595
366,24,43.0,Manchester United,71.7,24.6,FirstHalf,Pass,Successful,18.0,70.9,9.7,8,1,8,0,0.024015,0.021221
434,30,5.0,Manchester United,49.9,50.1,FirstHalf,Pass,Successful,18.0,31.0,40.7,5,4,3,3,0.014846,0.011324
473,31,58.0,Manchester United,65.4,77.9,FirstHalf,Pass,Successful,18.0,83.0,84.8,7,6,10,6,0.018703,0.040670
514,33,31.0,Manchester United,64.9,76.7,FirstHalf,Pass,Successful,18.0,47.7,67.3,7,6,5,5,0.018703,0.014291
516,33,37.0,Manchester United,59.8,88.1,FirstHalf,Pass,Successful,18.0,47.8,66.1,7,7,5,5,0.017451,0.014291
523,34,4.0,Manchester United,69.6,73.6,FirstHalf,Pass,Successful,18.0,65.3,86.6,8,6,7,7,0.024015,0.017451
581,37,3.0,Manchester United,58.8,94.2,FirstHalf,Pass,Successful,18.0,71.0,97.2,6,7,8,7,0.014736,0.021221
676,42,12.0,Manchester United,65.8,70.9,FirstHalf,Pass,Successful,18.0,58.9,71.2,8,5,7,5,0.024122,0.019351
679,42,21.0,Manchester United,60.9,69.4,FirstHalf,Pass,Successful,18.0,63.1,53.0,7,5,7,4,0.019351,0.019971
716,44,12.0,Manchester United,70.1,26.8,FirstHalf,Pass,Successful,18.0,65.0,19.7,8,2,7,1,0.024122,0.018703
752,45,12.0,Manchester United,67.9,29.1,FirstHalf,Pass,Successful,18.0,57.1,11.7,8,2,6,0,0.024122,0.014736
789,45,31.0,Manchester United,37.6,80.9,SecondHalf,Pass,Successful,18.0,38.4,87.4,3,6,4,7,0.010595,0.011263
838,47,46.0,Manchester United,24.3,65.1,SecondHalf,Pass,Successful,18.0,29.2,36.7,1,5,3,2,0.009777,0.011105
879,49,22.0,Manchester United,41.5,9.2,SecondHalf,Pass,Successful,18.0,47.7,14.3,4,0,5,1,0.011263,0.013845
884,49,34.0,Manchester United,56.5,7.7,SecondHalf,Pass,Successful,18.0,45.1,61.7,6,0,5,5,0.014736,0.014291
887,49,46.0,Manchester United,70.3,33.9,SecondHalf,Pass,Successful,18.0,74.7,27.1,8,2,9,2,0.024122,0.028552
970,56,26.0,Manchester United,63.8,18.2,SecondHalf,Pass,Successful,18.0,77.2,3.2,7,1,9,0,0.018703,0.027563

In [28]:
df['xT'] = df['end_zone_value'] - df['start_zone_value']

<ipython-input-28-a267dce9eb99>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['xT'] = df['end_zone_value'] - df['start_zone_value']

In [29]:
df.head(25)

,minute,second,teamId,x,y,period,type,outcome,playerId,endX,endY,x1_bin,y1_bin,x2_bin,y2_bin,start_zone_value,end_zone_value,xT
2,0,0.0,Manchester United,49.9,50.0,FirstHalf,Pass,Successful,18.0,31.5,59.6,5,4,3,4,0.014846,0.011324,-0.003522
119,6,11.0,Manchester United,65.4,96.8,FirstHalf,Pass,Successful,18.0,63.3,87.8,7,7,7,7,0.017451,0.017451,0.000000
130,6,55.0,Manchester United,69.8,30.3,FirstHalf,Pass,Successful,18.0,74.4,18.8,8,2,9,1,0.024122,0.029533,0.005410
133,7,1.0,Manchester United,84.3,23.3,FirstHalf,Pass,Successful,18.0,86.0,20.0,10,1,10,1,0.040670,0.040670,0.000000
185,12,20.0,Manchester United,39.0,64.8,FirstHalf,Pass,Successful,18.0,32.8,72.9,3,5,3,5,0.011105,0.011105,0.000000
197,12,50.0,Manchester United,43.0,70.0,FirstHalf,Pass,Successful,18.0,41.0,96.9,4,5,4,7,0.012692,0.011263,-0.001429
286,19,9.0,Manchester United,69.5,74.5,FirstHalf,Pass,Successful,18.0,59.9,71.1,8,6,7,5,0.024015,0.019351,-0.004664
336,22,57.0,Manchester United,37.0,89.6,FirstHalf,Pass,Successful,18.0,32.8,81.4,3,7,3,6,0.009777,0.010595,0.000818
366,24,43.0,Manchester United,71.7,24.6,FirstHalf,Pass,Successful,18.0,70.9,9.7,8,1,8,0,0.024015,0.021221,-0.002794
434,30,5.0,Manchester United,49.9,50.1,FirstHalf,Pass,Successful,18.0,31.0,40.7,5,4,3,3,0.014846,0.011324,-0.003522
473,31,58.0,Manchester United,65.4,77.9,FirstHalf,Pass,Successful,18.0,83.0,84.8,7,6,10,6,0.018703,0.040670,0.021966
514,33,31.0,Manchester United,64.9,76.7,FirstHalf,Pass,Successful,18.0,47.7,67.3,7,6,5,5,0.018703,0.014291,-0.004412
516,33,37.0,Manchester United,59.8,88.1,FirstHalf,Pass,Successful,18.0,47.8,66.1,7,7,5,5,0.017451,0.014291,-0.003159
523,34,4.0,Manchester United,69.6,73.6,FirstHalf,Pass,Successful,18.0,65.3,86.6,8,6,7,7,0.024015,0.017451,-0.006565
581,37,3.0,Manchester United,58.8,94.2,FirstHalf,Pass,Successful,18.0,71.0,97.2,6,7,8,7,0.014736,0.021221,0.006485
676,42,12.0,Manchester United,65.8,70.9,FirstHalf,Pass,Successful,18.0,58.9,71.2,8,5,7,5,0.024122,0.019351,-0.004771
679,42,21.0,Manchester United,60.9,69.4,FirstHalf,Pass,Successful,18.0,63.1,53.0,7,5,7,4,0.019351,0.019971,0.000619
716,44,12.0,Manchester United,70.1,26.8,FirstHalf,Pass,Successful,18.0,65.0,19.7,8,2,7,1,0.024122,0.018703,-0.005419
752,45,12.0,Manchester United,67.9,29.1,FirstHalf,Pass,Successful,18.0,57.1,11.7,8,2,6,0,0.024122,0.014736,-0.009386
789,45,31.0,Manchester United,37.6,80.9,SecondHalf,Pass,Successful,18.0,38.4,87.4,3,6,4,7,0.010595,0.011263,0.000668
838,47,46.0,Manchester United,24.3,65.1,SecondHalf,Pass,Successful,18.0,29.2,36.7,1,5,3,2,0.009777,0.011105,0.001327
879,49,22.0,Manchester United,41.5,9.2,SecondHalf,Pass,Successful,18.0,47.7,14.3,4,0,5,1,0.011263,0.013845,0.002583
884,49,34.0,Manchester United,56.5,7.7,SecondHalf,Pass,Successful,18.0,45.1,61.7,6,0,5,5,0.014736,0.014291,-0.000445
887,49,46.0,Manchester United,70.3,33.9,SecondHalf,Pass,Successful,18.0,74.7,27.1,8,2,9,2,0.024122,0.028552,0.004430
970,56,26.0,Manchester United,63.8,18.2,SecondHalf,Pass,Successful,18.0,77.2,3.2,7,1,9,0,0.018703,0.027563,0.008860

In [30]:
df.xT.sum()

0.07051732999999999

In [ ]:
f